[project]
name = "geodesic-toolbox"
version = "0.1.0"
description = "This package allows to compute geodesic distances/trajectories between points on a Riemannian manifold. The metric is defined by the user and can be parametrized by a neural network. It also support sampling as well as Randers metrics."
readme = "README.md"
authors = [
    { name = "Theau Blanchard", email = "theau.blanchard@inria.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.2",
    "kmedoids>=0.5.5",
    "networkx>=3.6.1",
    "numpy>=2.5.2",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.1",
    "torch>=2.13.0",
    "torchcurves>=0.3.1",
    "torchdiffeq>=0.2.5",
    "tqdm>=4.70.0",
]

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
